<a href="https://colab.research.google.com/github/rahulbordoloi/PyTorch/blob/master/PyTorch_Basics_Tensors_%26_Gradients.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# PyTorch Basics : Tensors & Gradients

# Importing & Installing Dependencies

In [ ]:
!pip install torch

In [1]:
import torch

# Tensors

In [ ]:
# Number
t1 = torch.tensor(4.)
t1, t1.dtype

(tensor(4.), torch.float32)

In [ ]:
# Vector
t2 = torch.tensor([1,2,3,4])
t2, t2.dtype

(tensor([1, 2, 3, 4]), torch.int64)

In [ ]:
# Matrix
x = [
     [1,2,3],
     [4,5,6], 
     [7,8,9]
     ]
t3 = torch.tensor(x)
x, t3, t3.dtype

([[1, 2, 3], [4, 5, 6], [7, 8, 9]], tensor([[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]), torch.int64)

In [ ]:
t1.shape, t2.shape, t3.shape

(torch.Size([]), torch.Size([4]), torch.Size([3, 3]))

In [8]:
torch.zeros([2,4], dtype=torch.float64)

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.]], dtype=torch.float64)

In [9]:
cuda0 = torch.device('cuda:0')
torch.ones([2, 4], dtype = torch.float64, device = cuda0)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.]], device='cuda:0', dtype=torch.float64)

# Tensor Operations and Gradients

In [ ]:
# Create Tensors
x = torch.tensor(3.)
w = torch.tensor(4., requires_grad=True)
b = torch.tensor(5., requires_grad=True)
x, w, b

(tensor(3.), tensor(4., requires_grad=True), tensor(5., requires_grad=True))

In [ ]:
# Arithmetic Operations
y = w * x + b
y

tensor(17., grad_fn=<AddBackward0>)

We can automatically compute the derivative of `y` w.r.t. the tensors that have `requires_grad` set to `True` i.e. w and b. To compute the derivatives, we can call the `.backward` method on our result `y`.

In [ ]:
# Compute Derivatives
y.backward()

The derivates of `y` w.r.t the input tensors are stored in the `.grad` property of the respective tensors.

In [ ]:
# Display Gradients
print('dy/dx:', x.grad)
print('dy/dw:', w.grad)
print('dy/db:', b.grad)

dy/dx: None
dy/dw: tensor(3.)
dy/db: tensor(1.)


The "grad" in `w.grad` stands for gradient, which is another term for derivative, used mainly when dealing with matrices. 

# Interoperability with Numpy

Here's how we create an array in Numpy:

In [2]:
import numpy as np

x = np.array([[1, 2], [3, 4.]])
x

array([[1., 2.],
       [3., 4.]])

In [4]:
# Converting the numpy array to a torch tensor.
y = torch.from_numpy(x)        # Creates the array on the same memory allocation
y

tensor([[1., 2.],
        [3., 4.]], dtype=torch.float64)

OR

In [5]:
y = torch.tensor(x)        # Creates the array on the a new memory allocation
y

tensor([[1., 2.],
        [3., 4.]], dtype=torch.float64)

In [6]:
x.dtype, y.dtype

(dtype('float64'), torch.float64)

In [7]:
# Converting a torch tensor to a numpy array
z = y.numpy()
z

array([[1., 2.],
       [3., 4.]])

# References

1.  https://pytorch.org/docs/stable/tensors.html
2.  https://github.com/yunjey/pytorch-tutorial